### ISSUE TITLE
感谢大佬分享。有个小疑问，为什么知乎、微博、小红书、公众号这些没有收录进来呢？这些不适合独立开发者发布产品吗？

### ISSUE THREAD

**Issue by Fr3027** [naxiaoduo/1000UserGuide#1]

**Comment by naxiaoduo** [comment]
回答：关于您提到的知乎、微博、小红书、公众号等平台确实都是非常流行的社交媒体平台，拥有大量的用户群体，对于独立开发者来说，这些平台也是非常好的推销渠道。

只不过，咱们产品阶段不同，采用的推销策略也是不同的。

早期阶段，可以先通过这些一次性渠道（大多数都是一次性的提交渠道），来试试水，验证验证效果反馈，再打磨打磨你的产品。
当你的产品，得到验证，需要持续推销的时候，这时候社交媒体这些大平台就派上用场了。你可以花一半时候打磨产品，一半时间更新内容进行持续推销。

1000UserGuide 的目标是帮助独立开发者和早期创业者，找到前1000个早期用户来验证他们的产品想法，并获得宝贵的反馈意见。

这些渠道的操作简单易行，推广成本低廉，方便独立开发者使用。

当然，也不是所有的产品都适用，这取决于你的产品是什么？你的目标人群在哪里。

你的目标人群在哪里，你就在哪里推销它。

关于社交媒体的说明，[查看这里](https://blog.csdn.net/xiaogeyilang/article/details/137553226)

![My_Photor_1713677295493](https://github.com/naxiaoduo/1000UserGuide/assets/2410694/bb918622-6319-4170-b990-1d79d57b406b)

**Comment by Fr3027** [comment]
感谢回复。
也就是说社交媒体账号需要长期运营、长期输出价值积累一定量的粉丝或知名度，才能比较好发挥出推广的作用。

**Comment by naxiaoduo** [comment]
> 感谢回复。 无论社交媒体账号需要长期运营、长期输出价值积累一定量的粉丝或品牌，才能比较好发挥出推广的作用。

社交媒体平台更适合持续推销。如果你有足够的时间可以腾出，那么社交媒体也可以一开始就做起来的，而且曝光度更大一些，尤其是面向大众的产品，非常适合。

**Comment by Fr3027** [comment]
谢谢建议，我打算两种方式结合起来😁

**Comment by Fr3027** [comment]
done
