### ISSUE TITLE
关于吾爱破解论坛

### ISSUE THREAD

**Issue by fanchenio** [naxiaoduo/1000UserGuide#2]
论坛发帖子不能带有任何广告形式，会被删帖，特别是原创区，发布你自己的作品，作品里面不能带官网，任何网址都不行，这个网站就别再这里推荐了吧。。。

**Comment by naxiaoduo** [comment]
> 论坛发帖子不能带有任何广告形式，会被删帖，特别是原创区，发布你自己的作品，作品里面不能带官网，任何网址都不行，这个网站就别再这里推荐了吧。。。

你在任何地方直接打广告，都没有人会搭理你。所以，你不要以你自己的认识来要求别人。

**Comment by naxiaoduo** [comment]
> 论坛发帖子不能带有任何广告形式，会被删帖，特别是原创区，发布你自己的作品，作品里面不能带官网，任何网址都不行，这个网站就别再这里推荐了吧。。。

另外，如果你在Reddit发帖，直接打个广告，不遵守版规，一样会被封号。多去看看别人的营销案例，别的开发者、创业者如何通过“软营销”来实现获客的，这很重要。

**Comment by fanchenio** [comment]
> > 论坛发帖子不能带有任何广告形式，会被删帖，特别是原创区，发布你自己的作品，作品里面不能带官网，任何网址都不行，这个网站就别再这里推荐了吧。。。
> 
> 你在任何地方直接打广告，都没有人会搭理你。所以，你不要以你自己的认识来要求别人。

我说的广告的意思就是，在软件里面加上自己的官网，所以你说的独立开发者上这个论坛去宣传能宣传？

**Comment by fanchenio** [comment]
算了，当我没说，关了，拜拜。
