### ISSUE TITLE
能否帮忙收录 独立开发者导航站，先谢过啦 ❤

### ISSUE THREAD

**Issue by javayhu** [naxiaoduo/1000UserGuide#5]
https://www.indiehackers.site/

独立开发者导航站，发掘最优秀的产品工具，助力你快速发布你的下一个应用。

网站站主要提供3个核心功能：产品工具、指南教程和独立应用，帮助独立开发者快速找到最适合的工具，应用到独立产品，加速独立产品上线。

![og8](https://github.com/naxiaoduo/1000UserGuide/assets/1982582/abe1180b-06ec-43f8-9597-12b07786facc)

![og2](https://github.com/naxiaoduo/1000UserGuide/assets/1982582/71ee767f-8f52-4bb9-9428-779eb6e1fa1d)

**Comment by naxiaoduo** [comment]
> https://www.indiehackers.site/

您好，晚一些我再更新加入哈。

**Comment by javayhu** [comment]
看到啦，非常感谢 ❤
